//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsicologoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PsicologoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Clinica")]
    public partial class PsicologoDC : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string CorreoField;
        
        private string DepartamentoField;
        
        private string DistritoField;
        
        private string EspecialidadField;
        
        private short EstadeField;
        
        private short EstadoField;
        
        private string EstadoPsicoField;
        
        private System.Nullable<System.DateTime> Fecha_registroField;
        
        private System.Nullable<System.DateTime> Fecha_ult_modificacionField;
        
        private byte[] FotoField;
        
        private short Id_psicologoField;
        
        private string Id_ubigeoField;
        
        private string NombreField;
        
        private string ProvinciaField;
        
        private string TelefonoField;
        
        private string Usuario_registroField;
        
        private string Usuario_ult_modificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CorreoField, value) != true))
                {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true))
                {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistritoField, value) != true))
                {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad
        {
            get
            {
                return this.EspecialidadField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true))
                {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estade
        {
            get
            {
                return this.EstadeField;
            }
            set
            {
                if ((this.EstadeField.Equals(value) != true))
                {
                    this.EstadeField = value;
                    this.RaisePropertyChanged("Estade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                if ((this.EstadoField.Equals(value) != true))
                {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoPsico
        {
            get
            {
                return this.EstadoPsicoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EstadoPsicoField, value) != true))
                {
                    this.EstadoPsicoField = value;
                    this.RaisePropertyChanged("EstadoPsico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_registro
        {
            get
            {
                return this.Fecha_registroField;
            }
            set
            {
                if ((this.Fecha_registroField.Equals(value) != true))
                {
                    this.Fecha_registroField = value;
                    this.RaisePropertyChanged("Fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_ult_modificacion
        {
            get
            {
                return this.Fecha_ult_modificacionField;
            }
            set
            {
                if ((this.Fecha_ult_modificacionField.Equals(value) != true))
                {
                    this.Fecha_ult_modificacionField = value;
                    this.RaisePropertyChanged("Fecha_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FotoField, value) != true))
                {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_psicologo
        {
            get
            {
                return this.Id_psicologoField;
            }
            set
            {
                if ((this.Id_psicologoField.Equals(value) != true))
                {
                    this.Id_psicologoField = value;
                    this.RaisePropertyChanged("Id_psicologo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_ubigeo
        {
            get
            {
                return this.Id_ubigeoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.Id_ubigeoField, value) != true))
                {
                    this.Id_ubigeoField = value;
                    this.RaisePropertyChanged("Id_ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NombreField, value) != true))
                {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true))
                {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true))
                {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_registro
        {
            get
            {
                return this.Usuario_registroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.Usuario_registroField, value) != true))
                {
                    this.Usuario_registroField = value;
                    this.RaisePropertyChanged("Usuario_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_ult_modificacion
        {
            get
            {
                return this.Usuario_ult_modificacionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.Usuario_ult_modificacionField, value) != true))
                {
                    this.Usuario_ult_modificacionField = value;
                    this.RaisePropertyChanged("Usuario_ult_modificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PsicologoService.IServicioPsicologo")]
    public interface IServicioPsicologo
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/ConsultarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/ConsultarPsicologoResponse")]
        PsicologoService.PsicologoDC ConsultarPsicologo(short strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/ConsultarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/ConsultarPsicologoResponse")]
        System.Threading.Tasks.Task<PsicologoService.PsicologoDC> ConsultarPsicologoAsync(short strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/ListarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/ListarPsicologoResponse")]
        System.Collections.Generic.List<PsicologoService.PsicologoDC> ListarPsicologo(short Estade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/ListarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/ListarPsicologoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PsicologoService.PsicologoDC>> ListarPsicologoAsync(short Estade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/InsertarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/InsertarPsicologoResponse")]
        bool InsertarPsicologo(PsicologoService.PsicologoDC objPsicologoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/InsertarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/InsertarPsicologoResponse")]
        System.Threading.Tasks.Task<bool> InsertarPsicologoAsync(PsicologoService.PsicologoDC objPsicologoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/ActualizarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/ActualizarPsicologoResponse")]
        bool ActualizarPsicologo(PsicologoService.PsicologoDC objPsicologoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/ActualizarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/ActualizarPsicologoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPsicologoAsync(PsicologoService.PsicologoDC objPsicologoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/EliminarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/EliminarPsicologoResponse")]
        bool EliminarPsicologo(short strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPsicologo/EliminarPsicologo", ReplyAction="http://tempuri.org/IServicioPsicologo/EliminarPsicologoResponse")]
        System.Threading.Tasks.Task<bool> EliminarPsicologoAsync(short strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioPsicologoChannel : PsicologoService.IServicioPsicologo, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioPsicologoClient : System.ServiceModel.ClientBase<PsicologoService.IServicioPsicologo>, PsicologoService.IServicioPsicologo
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioPsicologoClient() : 
                base(ServicioPsicologoClient.GetDefaultBinding(), ServicioPsicologoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioPsicologo.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPsicologoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioPsicologoClient.GetBindingForEndpoint(endpointConfiguration), ServicioPsicologoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPsicologoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioPsicologoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPsicologoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioPsicologoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPsicologoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PsicologoService.PsicologoDC ConsultarPsicologo(short strCodigo)
        {
            return base.Channel.ConsultarPsicologo(strCodigo);
        }
        
        public System.Threading.Tasks.Task<PsicologoService.PsicologoDC> ConsultarPsicologoAsync(short strCodigo)
        {
            return base.Channel.ConsultarPsicologoAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<PsicologoService.PsicologoDC> ListarPsicologo(short Estade)
        {
            return base.Channel.ListarPsicologo(Estade);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PsicologoService.PsicologoDC>> ListarPsicologoAsync(short Estade)
        {
            return base.Channel.ListarPsicologoAsync(Estade);
        }
        
        public bool InsertarPsicologo(PsicologoService.PsicologoDC objPsicologoDC)
        {
            return base.Channel.InsertarPsicologo(objPsicologoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarPsicologoAsync(PsicologoService.PsicologoDC objPsicologoDC)
        {
            return base.Channel.InsertarPsicologoAsync(objPsicologoDC);
        }
        
        public bool ActualizarPsicologo(PsicologoService.PsicologoDC objPsicologoDC)
        {
            return base.Channel.ActualizarPsicologo(objPsicologoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPsicologoAsync(PsicologoService.PsicologoDC objPsicologoDC)
        {
            return base.Channel.ActualizarPsicologoAsync(objPsicologoDC);
        }
        
        public bool EliminarPsicologo(short strCodigo)
        {
            return base.Channel.EliminarPsicologo(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPsicologoAsync(short strCodigo)
        {
            return base.Channel.EliminarPsicologoAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPsicologo))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPsicologo))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Clinica/ServicioPsicologo/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioPsicologoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioPsicologo);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioPsicologoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioPsicologo);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioPsicologo,
        }
    }
}
