//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CitaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Clinica")]
    public partial class CitaDC : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int confirmacion_asistenciaField;
        
        private System.Nullable<int> duracionField;
        
        private int estadeField;
        
        private int estadoField;
        
        private string estado_pagoField;
        
        private System.DateTime fechaField;
        
        private System.DateTime fecha_registroField;
        
        private System.DateTime fecha_ult_modificacionField;
        
        private System.TimeSpan horaField;
        
        private int idField;
        
        private int id_consultorioField;
        
        private int id_historialField;
        
        private int id_pacienteField;
        
        private int id_psicologoField;
        
        private string motivo_citaField;
        
        private string pacienteField;
        
        private System.Nullable<decimal> precioField;
        
        private string psicologoField;
        
        private string tipo_citaField;
        
        private string usuario_registroField;
        
        private string usuario_ult_modificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int confirmacion_asistencia
        {
            get
            {
                return this.confirmacion_asistenciaField;
            }
            set
            {
                if ((this.confirmacion_asistenciaField.Equals(value) != true))
                {
                    this.confirmacion_asistenciaField = value;
                    this.RaisePropertyChanged("confirmacion_asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> duracion
        {
            get
            {
                return this.duracionField;
            }
            set
            {
                if ((this.duracionField.Equals(value) != true))
                {
                    this.duracionField = value;
                    this.RaisePropertyChanged("duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estade
        {
            get
            {
                return this.estadeField;
            }
            set
            {
                if ((this.estadeField.Equals(value) != true))
                {
                    this.estadeField = value;
                    this.RaisePropertyChanged("estade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                if ((this.estadoField.Equals(value) != true))
                {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_pago
        {
            get
            {
                return this.estado_pagoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.estado_pagoField, value) != true))
                {
                    this.estado_pagoField = value;
                    this.RaisePropertyChanged("estado_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                if ((this.fechaField.Equals(value) != true))
                {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_registro
        {
            get
            {
                return this.fecha_registroField;
            }
            set
            {
                if ((this.fecha_registroField.Equals(value) != true))
                {
                    this.fecha_registroField = value;
                    this.RaisePropertyChanged("fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ult_modificacion
        {
            get
            {
                return this.fecha_ult_modificacionField;
            }
            set
            {
                if ((this.fecha_ult_modificacionField.Equals(value) != true))
                {
                    this.fecha_ult_modificacionField = value;
                    this.RaisePropertyChanged("fecha_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                if ((this.horaField.Equals(value) != true))
                {
                    this.horaField = value;
                    this.RaisePropertyChanged("hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField.Equals(value) != true))
                {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_consultorio
        {
            get
            {
                return this.id_consultorioField;
            }
            set
            {
                if ((this.id_consultorioField.Equals(value) != true))
                {
                    this.id_consultorioField = value;
                    this.RaisePropertyChanged("id_consultorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_historial
        {
            get
            {
                return this.id_historialField;
            }
            set
            {
                if ((this.id_historialField.Equals(value) != true))
                {
                    this.id_historialField = value;
                    this.RaisePropertyChanged("id_historial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_paciente
        {
            get
            {
                return this.id_pacienteField;
            }
            set
            {
                if ((this.id_pacienteField.Equals(value) != true))
                {
                    this.id_pacienteField = value;
                    this.RaisePropertyChanged("id_paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_psicologo
        {
            get
            {
                return this.id_psicologoField;
            }
            set
            {
                if ((this.id_psicologoField.Equals(value) != true))
                {
                    this.id_psicologoField = value;
                    this.RaisePropertyChanged("id_psicologo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motivo_cita
        {
            get
            {
                return this.motivo_citaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.motivo_citaField, value) != true))
                {
                    this.motivo_citaField = value;
                    this.RaisePropertyChanged("motivo_cita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente
        {
            get
            {
                return this.pacienteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.pacienteField, value) != true))
                {
                    this.pacienteField = value;
                    this.RaisePropertyChanged("paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                if ((this.precioField.Equals(value) != true))
                {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psicologo
        {
            get
            {
                return this.psicologoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.psicologoField, value) != true))
                {
                    this.psicologoField = value;
                    this.RaisePropertyChanged("psicologo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_cita
        {
            get
            {
                return this.tipo_citaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.tipo_citaField, value) != true))
                {
                    this.tipo_citaField = value;
                    this.RaisePropertyChanged("tipo_cita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_registro
        {
            get
            {
                return this.usuario_registroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.usuario_registroField, value) != true))
                {
                    this.usuario_registroField = value;
                    this.RaisePropertyChanged("usuario_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_ult_modificacion
        {
            get
            {
                return this.usuario_ult_modificacionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.usuario_ult_modificacionField, value) != true))
                {
                    this.usuario_ult_modificacionField = value;
                    this.RaisePropertyChanged("usuario_ult_modificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CitaService.IServicioCita")]
    public interface IServicioCita
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPacientePorFecha", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPacientePorFechaResponse")]
        System.Collections.Generic.List<CitaService.CitaDC> ListarCitasPacientePorFecha(int codigo, System.DateTime FecIni, System.DateTime FecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPacientePorFecha", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPacientePorFechaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CitaService.CitaDC>> ListarCitasPacientePorFechaAsync(int codigo, System.DateTime FecIni, System.DateTime FecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPorFecha", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPorFechaResponse")]
        System.Collections.Generic.List<CitaService.CitaDC> ListarCitasPorFecha(System.DateTime FecIni, System.DateTime FecFin, int estade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPorFecha", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPorFechaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CitaService.CitaDC>> ListarCitasPorFechaAsync(System.DateTime FecIni, System.DateTime FecFin, int estade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ConsultarCita", ReplyAction="http://tempuri.org/IServicioCita/ConsultarCitaResponse")]
        CitaService.CitaDC ConsultarCita(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ConsultarCita", ReplyAction="http://tempuri.org/IServicioCita/ConsultarCitaResponse")]
        System.Threading.Tasks.Task<CitaService.CitaDC> ConsultarCitaAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/InsertarCita", ReplyAction="http://tempuri.org/IServicioCita/InsertarCitaResponse")]
        bool InsertarCita(CitaService.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/InsertarCita", ReplyAction="http://tempuri.org/IServicioCita/InsertarCitaResponse")]
        System.Threading.Tasks.Task<bool> InsertarCitaAsync(CitaService.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ActualizarCita", ReplyAction="http://tempuri.org/IServicioCita/ActualizarCitaResponse")]
        bool ActualizarCita(CitaService.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ActualizarCita", ReplyAction="http://tempuri.org/IServicioCita/ActualizarCitaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCitaAsync(CitaService.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarCita", ReplyAction="http://tempuri.org/IServicioCita/EliminarCitaResponse")]
        bool EliminarCita(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarCita", ReplyAction="http://tempuri.org/IServicioCita/EliminarCitaResponse")]
        System.Threading.Tasks.Task<bool> EliminarCitaAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ExisteCitaConflicto", ReplyAction="http://tempuri.org/IServicioCita/ExisteCitaConflictoResponse")]
        bool ExisteCitaConflicto(int idPsicologo, int idPaciente, System.DateTime fecha, System.TimeSpan hora, int duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ExisteCitaConflicto", ReplyAction="http://tempuri.org/IServicioCita/ExisteCitaConflictoResponse")]
        System.Threading.Tasks.Task<bool> ExisteCitaConflictoAsync(int idPsicologo, int idPaciente, System.DateTime fecha, System.TimeSpan hora, int duracion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioCitaChannel : CitaService.IServicioCita, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioCitaClient : System.ServiceModel.ClientBase<CitaService.IServicioCita>, CitaService.IServicioCita
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioCitaClient() : 
                base(ServicioCitaClient.GetDefaultBinding(), ServicioCitaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCita.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioCitaClient.GetBindingForEndpoint(endpointConfiguration), ServicioCitaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioCitaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioCitaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<CitaService.CitaDC> ListarCitasPacientePorFecha(int codigo, System.DateTime FecIni, System.DateTime FecFin)
        {
            return base.Channel.ListarCitasPacientePorFecha(codigo, FecIni, FecFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CitaService.CitaDC>> ListarCitasPacientePorFechaAsync(int codigo, System.DateTime FecIni, System.DateTime FecFin)
        {
            return base.Channel.ListarCitasPacientePorFechaAsync(codigo, FecIni, FecFin);
        }
        
        public System.Collections.Generic.List<CitaService.CitaDC> ListarCitasPorFecha(System.DateTime FecIni, System.DateTime FecFin, int estade)
        {
            return base.Channel.ListarCitasPorFecha(FecIni, FecFin, estade);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CitaService.CitaDC>> ListarCitasPorFechaAsync(System.DateTime FecIni, System.DateTime FecFin, int estade)
        {
            return base.Channel.ListarCitasPorFechaAsync(FecIni, FecFin, estade);
        }
        
        public CitaService.CitaDC ConsultarCita(int codigo)
        {
            return base.Channel.ConsultarCita(codigo);
        }
        
        public System.Threading.Tasks.Task<CitaService.CitaDC> ConsultarCitaAsync(int codigo)
        {
            return base.Channel.ConsultarCitaAsync(codigo);
        }
        
        public bool InsertarCita(CitaService.CitaDC objCitaDC)
        {
            return base.Channel.InsertarCita(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarCitaAsync(CitaService.CitaDC objCitaDC)
        {
            return base.Channel.InsertarCitaAsync(objCitaDC);
        }
        
        public bool ActualizarCita(CitaService.CitaDC objCitaDC)
        {
            return base.Channel.ActualizarCita(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCitaAsync(CitaService.CitaDC objCitaDC)
        {
            return base.Channel.ActualizarCitaAsync(objCitaDC);
        }
        
        public bool EliminarCita(int codigo)
        {
            return base.Channel.EliminarCita(codigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCitaAsync(int codigo)
        {
            return base.Channel.EliminarCitaAsync(codigo);
        }
        
        public bool ExisteCitaConflicto(int idPsicologo, int idPaciente, System.DateTime fecha, System.TimeSpan hora, int duracion)
        {
            return base.Channel.ExisteCitaConflicto(idPsicologo, idPaciente, fecha, hora, duracion);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteCitaConflictoAsync(int idPsicologo, int idPaciente, System.DateTime fecha, System.TimeSpan hora, int duracion)
        {
            return base.Channel.ExisteCitaConflictoAsync(idPsicologo, idPaciente, fecha, hora, duracion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCita))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCita))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Clinica/ServicioCita/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioCitaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCita);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioCitaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCita);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCita,
        }
    }
}
