//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Clinica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClinPsicologicaEntities : DbContext
    {
        public ClinPsicologicaEntities()
            : base("name=ClinPsicologicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_administrador> tb_administrador { get; set; }
        public virtual DbSet<tb_cita> tb_cita { get; set; }
        public virtual DbSet<tb_consultorio> tb_consultorio { get; set; }
        public virtual DbSet<tb_historial_clinico> tb_historial_clinico { get; set; }
        public virtual DbSet<tb_horario> tb_horario { get; set; }
        public virtual DbSet<tb_local> tb_local { get; set; }
        public virtual DbSet<tb_paciente> tb_paciente { get; set; }
        public virtual DbSet<tb_psicologo> tb_psicologo { get; set; }
        public virtual DbSet<tb_tratamiento> tb_tratamiento { get; set; }
        public virtual DbSet<tb_Ubigeo> tb_Ubigeo { get; set; }
        public virtual DbSet<tb_Usuarios> tb_Usuarios { get; set; }
    
        public virtual int usp_ActualizarAdministrador(Nullable<int> id_admin, string nombre, string apellido, string telefono, string correo, string ubigeo, Nullable<int> estado)
        {
            var id_adminParameter = id_admin.HasValue ?
                new ObjectParameter("id_admin", id_admin) :
                new ObjectParameter("id_admin", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarAdministrador", id_adminParameter, nombreParameter, apellidoParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter);
        }
    
        public virtual int usp_ActualizarCita(Nullable<int> id_cita, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hora, Nullable<int> id_psicologo, Nullable<int> id_paciente, Nullable<int> id_consultorio, Nullable<int> estado, string motivo_cita, Nullable<int> duracion, string tipo_cita, Nullable<decimal> precio, string estado_pago, Nullable<int> confirmacion_asistencia)
        {
            var id_citaParameter = id_cita.HasValue ?
                new ObjectParameter("id_cita", id_cita) :
                new ObjectParameter("id_cita", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(System.TimeSpan));
    
            var id_psicologoParameter = id_psicologo.HasValue ?
                new ObjectParameter("id_psicologo", id_psicologo) :
                new ObjectParameter("id_psicologo", typeof(int));
    
            var id_pacienteParameter = id_paciente.HasValue ?
                new ObjectParameter("id_paciente", id_paciente) :
                new ObjectParameter("id_paciente", typeof(int));
    
            var id_consultorioParameter = id_consultorio.HasValue ?
                new ObjectParameter("id_consultorio", id_consultorio) :
                new ObjectParameter("id_consultorio", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var motivo_citaParameter = motivo_cita != null ?
                new ObjectParameter("motivo_cita", motivo_cita) :
                new ObjectParameter("motivo_cita", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("duracion", duracion) :
                new ObjectParameter("duracion", typeof(int));
    
            var tipo_citaParameter = tipo_cita != null ?
                new ObjectParameter("tipo_cita", tipo_cita) :
                new ObjectParameter("tipo_cita", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var estado_pagoParameter = estado_pago != null ?
                new ObjectParameter("estado_pago", estado_pago) :
                new ObjectParameter("estado_pago", typeof(string));
    
            var confirmacion_asistenciaParameter = confirmacion_asistencia.HasValue ?
                new ObjectParameter("confirmacion_asistencia", confirmacion_asistencia) :
                new ObjectParameter("confirmacion_asistencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCita", id_citaParameter, fechaParameter, horaParameter, id_psicologoParameter, id_pacienteParameter, id_consultorioParameter, estadoParameter, motivo_citaParameter, duracionParameter, tipo_citaParameter, precioParameter, estado_pagoParameter, confirmacion_asistenciaParameter);
        }
    
        public virtual int usp_ActualizarConsultorio(Nullable<int> id_consultorio, string telefono, Nullable<System.TimeSpan> inicio, Nullable<System.TimeSpan> fin, Nullable<int> id_local)
        {
            var id_consultorioParameter = id_consultorio.HasValue ?
                new ObjectParameter("id_consultorio", id_consultorio) :
                new ObjectParameter("id_consultorio", typeof(int));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("inicio", inicio) :
                new ObjectParameter("inicio", typeof(System.TimeSpan));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("fin", fin) :
                new ObjectParameter("fin", typeof(System.TimeSpan));
    
            var id_localParameter = id_local.HasValue ?
                new ObjectParameter("id_local", id_local) :
                new ObjectParameter("id_local", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarConsultorio", id_consultorioParameter, telefonoParameter, inicioParameter, finParameter, id_localParameter);
        }
    
        public virtual int usp_ActualizarLocal(string id_local, string direccion, string telefono, string correo, Nullable<int> administrador, string ubigeo)
        {
            var id_localParameter = id_local != null ?
                new ObjectParameter("id_local", id_local) :
                new ObjectParameter("id_local", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var administradorParameter = administrador.HasValue ?
                new ObjectParameter("Administrador", administrador) :
                new ObjectParameter("Administrador", typeof(int));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarLocal", id_localParameter, direccionParameter, telefonoParameter, correoParameter, administradorParameter, ubigeoParameter);
        }
    
        public virtual int usp_ActualizarPaciente(Nullable<int> vid_pac, string vnom, string vape, string vgenero, string vtel, string vcorreo, string vid_ubigeo, Nullable<int> vestado, byte[] vfoto, Nullable<int> vedad)
        {
            var vid_pacParameter = vid_pac.HasValue ?
                new ObjectParameter("vid_pac", vid_pac) :
                new ObjectParameter("vid_pac", typeof(int));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vgeneroParameter = vgenero != null ?
                new ObjectParameter("vgenero", vgenero) :
                new ObjectParameter("vgenero", typeof(string));
    
            var vtelParameter = vtel != null ?
                new ObjectParameter("vtel", vtel) :
                new ObjectParameter("vtel", typeof(string));
    
            var vcorreoParameter = vcorreo != null ?
                new ObjectParameter("vcorreo", vcorreo) :
                new ObjectParameter("vcorreo", typeof(string));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vestadoParameter = vestado.HasValue ?
                new ObjectParameter("vestado", vestado) :
                new ObjectParameter("vestado", typeof(int));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vedadParameter = vedad.HasValue ?
                new ObjectParameter("vedad", vedad) :
                new ObjectParameter("vedad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarPaciente", vid_pacParameter, vnomParameter, vapeParameter, vgeneroParameter, vtelParameter, vcorreoParameter, vid_ubigeoParameter, vestadoParameter, vfotoParameter, vedadParameter);
        }
    
        public virtual int usp_ActualizarPsicologo(Nullable<int> id_psicologo, string nombre, string especialidad, byte[] foto, string telefono, string correo, Nullable<int> id_ubigeo, Nullable<int> estado)
        {
            var id_psicologoParameter = id_psicologo.HasValue ?
                new ObjectParameter("id_psicologo", id_psicologo) :
                new ObjectParameter("id_psicologo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var id_ubigeoParameter = id_ubigeo.HasValue ?
                new ObjectParameter("id_ubigeo", id_ubigeo) :
                new ObjectParameter("id_ubigeo", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarPsicologo", id_psicologoParameter, nombreParameter, especialidadParameter, fotoParameter, telefonoParameter, correoParameter, id_ubigeoParameter, estadoParameter);
        }
    
        public virtual int usp_ActualizarTratamiento(Nullable<int> id_tratamiento, string descripcion)
        {
            var id_tratamientoParameter = id_tratamiento.HasValue ?
                new ObjectParameter("id_tratamiento", id_tratamiento) :
                new ObjectParameter("id_tratamiento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarTratamiento", id_tratamientoParameter, descripcionParameter);
        }
    
        public virtual int usp_ActualizarUbigeo(string id_ubigeo, string idDepa, string idProv, string idDist, string departamento, string provincia, string distrito)
        {
            var id_ubigeoParameter = id_ubigeo != null ?
                new ObjectParameter("id_ubigeo", id_ubigeo) :
                new ObjectParameter("id_ubigeo", typeof(string));
    
            var idDepaParameter = idDepa != null ?
                new ObjectParameter("idDepa", idDepa) :
                new ObjectParameter("idDepa", typeof(string));
    
            var idProvParameter = idProv != null ?
                new ObjectParameter("idProv", idProv) :
                new ObjectParameter("idProv", typeof(string));
    
            var idDistParameter = idDist != null ?
                new ObjectParameter("idDist", idDist) :
                new ObjectParameter("idDist", typeof(string));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var provinciaParameter = provincia != null ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("Distrito", distrito) :
                new ObjectParameter("Distrito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarUbigeo", id_ubigeoParameter, idDepaParameter, idProvParameter, idDistParameter, departamentoParameter, provinciaParameter, distritoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarAdmin_Result> usp_ConsultarAdmin(Nullable<int> idAdministrador)
        {
            var idAdministradorParameter = idAdministrador.HasValue ?
                new ObjectParameter("IdAdministrador", idAdministrador) :
                new ObjectParameter("IdAdministrador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarAdmin_Result>("usp_ConsultarAdmin", idAdministradorParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCita_Result> usp_ConsultarCita(Nullable<int> id_cita)
        {
            var id_citaParameter = id_cita.HasValue ?
                new ObjectParameter("id_cita", id_cita) :
                new ObjectParameter("id_cita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCita_Result>("usp_ConsultarCita", id_citaParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarConsultorio_Result> usp_ConsultarConsultorio(Nullable<int> id_consultorio)
        {
            var id_consultorioParameter = id_consultorio.HasValue ?
                new ObjectParameter("id_consultorio", id_consultorio) :
                new ObjectParameter("id_consultorio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarConsultorio_Result>("usp_ConsultarConsultorio", id_consultorioParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarConsultoriosPorLocal_Result> usp_ConsultarConsultoriosPorLocal(string direccion)
        {
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarConsultoriosPorLocal_Result>("usp_ConsultarConsultoriosPorLocal", direccionParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarLocal_Result> usp_ConsultarLocal(Nullable<int> id_local)
        {
            var id_localParameter = id_local.HasValue ?
                new ObjectParameter("id_local", id_local) :
                new ObjectParameter("id_local", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarLocal_Result>("usp_ConsultarLocal", id_localParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarLocalesPorDepartamento_Result> usp_ConsultarLocalesPorDepartamento(string departamento)
        {
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarLocalesPorDepartamento_Result>("usp_ConsultarLocalesPorDepartamento", departamentoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarPaciente_Result> usp_ConsultarPaciente(Nullable<int> vid_pac)
        {
            var vid_pacParameter = vid_pac.HasValue ?
                new ObjectParameter("vid_pac", vid_pac) :
                new ObjectParameter("vid_pac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarPaciente_Result>("usp_ConsultarPaciente", vid_pacParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarPsicologo_Result> usp_ConsultarPsicologo(Nullable<int> id_psicologo)
        {
            var id_psicologoParameter = id_psicologo.HasValue ?
                new ObjectParameter("id_psicologo", id_psicologo) :
                new ObjectParameter("id_psicologo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarPsicologo_Result>("usp_ConsultarPsicologo", id_psicologoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarPsicologosPorLocal_Result> usp_ConsultarPsicologosPorLocal(string direccion)
        {
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarPsicologosPorLocal_Result>("usp_ConsultarPsicologosPorLocal", direccionParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarTratamiento_Result> usp_ConsultarTratamiento(Nullable<int> id_tratamiento)
        {
            var id_tratamientoParameter = id_tratamiento.HasValue ?
                new ObjectParameter("id_tratamiento", id_tratamiento) :
                new ObjectParameter("id_tratamiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarTratamiento_Result>("usp_ConsultarTratamiento", id_tratamientoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarUbigeo_Result> usp_ConsultarUbigeo(Nullable<int> id_ubigeo)
        {
            var id_ubigeoParameter = id_ubigeo.HasValue ?
                new ObjectParameter("id_ubigeo", id_ubigeo) :
                new ObjectParameter("id_ubigeo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUbigeo_Result>("usp_ConsultarUbigeo", id_ubigeoParameter);
        }
    
        public virtual int usp_DeleteAdministrador(Nullable<int> id_admin)
        {
            var id_adminParameter = id_admin.HasValue ?
                new ObjectParameter("id_admin", id_admin) :
                new ObjectParameter("id_admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteAdministrador", id_adminParameter);
        }
    
        public virtual int usp_DeleteConsultorio(Nullable<int> id_consultorio)
        {
            var id_consultorioParameter = id_consultorio.HasValue ?
                new ObjectParameter("id_consultorio", id_consultorio) :
                new ObjectParameter("id_consultorio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteConsultorio", id_consultorioParameter);
        }
    
        public virtual int usp_DeleteLocal(Nullable<int> id_Local)
        {
            var id_LocalParameter = id_Local.HasValue ?
                new ObjectParameter("id_Local", id_Local) :
                new ObjectParameter("id_Local", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteLocal", id_LocalParameter);
        }
    
        public virtual int usp_DeletePaciente(Nullable<int> id_paciente)
        {
            var id_pacienteParameter = id_paciente.HasValue ?
                new ObjectParameter("id_paciente", id_paciente) :
                new ObjectParameter("id_paciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeletePaciente", id_pacienteParameter);
        }
    
        public virtual int usp_DeletePsicologo(Nullable<int> id_Psicologo)
        {
            var id_PsicologoParameter = id_Psicologo.HasValue ?
                new ObjectParameter("id_Psicologo", id_Psicologo) :
                new ObjectParameter("id_Psicologo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeletePsicologo", id_PsicologoParameter);
        }
    
        public virtual int usp_DeleteTratamiento(Nullable<int> id_Tratamiento)
        {
            var id_TratamientoParameter = id_Tratamiento.HasValue ?
                new ObjectParameter("id_Tratamiento", id_Tratamiento) :
                new ObjectParameter("id_Tratamiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteTratamiento", id_TratamientoParameter);
        }
    
        public virtual int usp_EliminarAdministrador(Nullable<int> id_admin)
        {
            var id_adminParameter = id_admin.HasValue ?
                new ObjectParameter("id_admin", id_admin) :
                new ObjectParameter("id_admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarAdministrador", id_adminParameter);
        }
    
        public virtual int usp_EliminarCita(Nullable<int> id_cita)
        {
            var id_citaParameter = id_cita.HasValue ?
                new ObjectParameter("id_cita", id_cita) :
                new ObjectParameter("id_cita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCita", id_citaParameter);
        }
    
        public virtual int usp_EliminarConsultorio(Nullable<int> id_consultorio)
        {
            var id_consultorioParameter = id_consultorio.HasValue ?
                new ObjectParameter("id_consultorio", id_consultorio) :
                new ObjectParameter("id_consultorio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarConsultorio", id_consultorioParameter);
        }
    
        public virtual int usp_EliminarLocal(string id_local)
        {
            var id_localParameter = id_local != null ?
                new ObjectParameter("id_local", id_local) :
                new ObjectParameter("id_local", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarLocal", id_localParameter);
        }
    
        public virtual int usp_EliminarPaciente(Nullable<int> vid_pac)
        {
            var vid_pacParameter = vid_pac.HasValue ?
                new ObjectParameter("vid_pac", vid_pac) :
                new ObjectParameter("vid_pac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarPaciente", vid_pacParameter);
        }
    
        public virtual int usp_EliminarPsicologo(Nullable<int> id_psicologo)
        {
            var id_psicologoParameter = id_psicologo.HasValue ?
                new ObjectParameter("id_psicologo", id_psicologo) :
                new ObjectParameter("id_psicologo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarPsicologo", id_psicologoParameter);
        }
    
        public virtual int usp_EliminarTratamiento(Nullable<int> id_tratamiento)
        {
            var id_tratamientoParameter = id_tratamiento.HasValue ?
                new ObjectParameter("id_tratamiento", id_tratamiento) :
                new ObjectParameter("id_tratamiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarTratamiento", id_tratamientoParameter);
        }
    
        public virtual int usp_EliminarUbigeo(Nullable<int> id_ubigeo)
        {
            var id_ubigeoParameter = id_ubigeo.HasValue ?
                new ObjectParameter("id_ubigeo", id_ubigeo) :
                new ObjectParameter("id_ubigeo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarUbigeo", id_ubigeoParameter);
        }
    
        public virtual int usp_InsertAdministrador(string nombre, string apellido, string telefono, string correo, string ubigeo, Nullable<int> estado, Nullable<System.DateTime> fecha_registro, Nullable<System.DateTime> fecha_ult_modificacion, string usuario_registro, string usuario_ult_modificacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("Fecha_registro", fecha_registro) :
                new ObjectParameter("Fecha_registro", typeof(System.DateTime));
    
            var fecha_ult_modificacionParameter = fecha_ult_modificacion.HasValue ?
                new ObjectParameter("Fecha_ult_modificacion", fecha_ult_modificacion) :
                new ObjectParameter("Fecha_ult_modificacion", typeof(System.DateTime));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertAdministrador", nombreParameter, apellidoParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter, fecha_registroParameter, fecha_ult_modificacionParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_InsertarAdministrador(string nombre, string apellido, string telefono, string correo, string ubigeo, Nullable<int> estado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAdministrador", nombreParameter, apellidoParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter);
        }
    
        public virtual int usp_InsertarCita(Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hora, Nullable<int> id_psicologo, Nullable<int> id_paciente, Nullable<int> id_consultorio, Nullable<int> estado, string motivo_cita, Nullable<int> duracion, string tipo_cita, Nullable<decimal> precio, string estado_pago, Nullable<int> confirmacion_asistencia)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(System.TimeSpan));
    
            var id_psicologoParameter = id_psicologo.HasValue ?
                new ObjectParameter("id_psicologo", id_psicologo) :
                new ObjectParameter("id_psicologo", typeof(int));
    
            var id_pacienteParameter = id_paciente.HasValue ?
                new ObjectParameter("id_paciente", id_paciente) :
                new ObjectParameter("id_paciente", typeof(int));
    
            var id_consultorioParameter = id_consultorio.HasValue ?
                new ObjectParameter("id_consultorio", id_consultorio) :
                new ObjectParameter("id_consultorio", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var motivo_citaParameter = motivo_cita != null ?
                new ObjectParameter("motivo_cita", motivo_cita) :
                new ObjectParameter("motivo_cita", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("duracion", duracion) :
                new ObjectParameter("duracion", typeof(int));
    
            var tipo_citaParameter = tipo_cita != null ?
                new ObjectParameter("tipo_cita", tipo_cita) :
                new ObjectParameter("tipo_cita", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var estado_pagoParameter = estado_pago != null ?
                new ObjectParameter("estado_pago", estado_pago) :
                new ObjectParameter("estado_pago", typeof(string));
    
            var confirmacion_asistenciaParameter = confirmacion_asistencia.HasValue ?
                new ObjectParameter("confirmacion_asistencia", confirmacion_asistencia) :
                new ObjectParameter("confirmacion_asistencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCita", fechaParameter, horaParameter, id_psicologoParameter, id_pacienteParameter, id_consultorioParameter, estadoParameter, motivo_citaParameter, duracionParameter, tipo_citaParameter, precioParameter, estado_pagoParameter, confirmacion_asistenciaParameter);
        }
    
        public virtual int usp_InsertarConsultorio(string telefono, Nullable<System.TimeSpan> inicio, Nullable<System.TimeSpan> fin, Nullable<int> id_local, Nullable<System.DateTime> fecha_registro, Nullable<System.DateTime> fecha_ult_modificacion, string usuario_registro, string usuario_ult_modificacion)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.TimeSpan));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(System.TimeSpan));
    
            var id_localParameter = id_local.HasValue ?
                new ObjectParameter("Id_local", id_local) :
                new ObjectParameter("Id_local", typeof(int));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("Fecha_registro", fecha_registro) :
                new ObjectParameter("Fecha_registro", typeof(System.DateTime));
    
            var fecha_ult_modificacionParameter = fecha_ult_modificacion.HasValue ?
                new ObjectParameter("Fecha_ult_modificacion", fecha_ult_modificacion) :
                new ObjectParameter("Fecha_ult_modificacion", typeof(System.DateTime));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarConsultorio", telefonoParameter, inicioParameter, finParameter, id_localParameter, fecha_registroParameter, fecha_ult_modificacionParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_InsertarLocal(string direccion, string telefono, string correo, Nullable<int> id_administrador, string id_ubigeo, string usuario_registro, string usuario_ult_modificacion)
        {
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var id_administradorParameter = id_administrador.HasValue ?
                new ObjectParameter("Id_administrador", id_administrador) :
                new ObjectParameter("Id_administrador", typeof(int));
    
            var id_ubigeoParameter = id_ubigeo != null ?
                new ObjectParameter("Id_ubigeo", id_ubigeo) :
                new ObjectParameter("Id_ubigeo", typeof(string));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarLocal", direccionParameter, telefonoParameter, correoParameter, id_administradorParameter, id_ubigeoParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_InsertarPaciente(string nombre, string apellido, string genero, string telefono, string correo, string ubigeo, Nullable<int> estado, byte[] foto, Nullable<System.DateTime> fecha_Naci, string usuario_registro, string usuario_ult_modificacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            var fecha_NaciParameter = fecha_Naci.HasValue ?
                new ObjectParameter("Fecha_Naci", fecha_Naci) :
                new ObjectParameter("Fecha_Naci", typeof(System.DateTime));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarPaciente", nombreParameter, apellidoParameter, generoParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter, fotoParameter, fecha_NaciParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_InsertarPsicologo(string nombre, string especialidad, string telefono, string correo, string ubigeo, Nullable<int> estado, byte[] foto, string usuario_registro, string usuario_ult_modificacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("Especialidad", especialidad) :
                new ObjectParameter("Especialidad", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarPsicologo", nombreParameter, especialidadParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter, fotoParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_InsertarTratamiento(string descripcion, Nullable<System.DateTime> fecha_registro, Nullable<System.DateTime> fecha_ult_modificacion, string usuario_registro, string usuario_ult_modificacion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("Fecha_registro", fecha_registro) :
                new ObjectParameter("Fecha_registro", typeof(System.DateTime));
    
            var fecha_ult_modificacionParameter = fecha_ult_modificacion.HasValue ?
                new ObjectParameter("Fecha_ult_modificacion", fecha_ult_modificacion) :
                new ObjectParameter("Fecha_ult_modificacion", typeof(System.DateTime));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarTratamiento", descripcionParameter, fecha_registroParameter, fecha_ult_modificacionParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_InsertarUbigeo(string id_ubigeo, string idDepa, string idProv, string idDist, string departamento, string provincia, string distrito)
        {
            var id_ubigeoParameter = id_ubigeo != null ?
                new ObjectParameter("id_ubigeo", id_ubigeo) :
                new ObjectParameter("id_ubigeo", typeof(string));
    
            var idDepaParameter = idDepa != null ?
                new ObjectParameter("idDepa", idDepa) :
                new ObjectParameter("idDepa", typeof(string));
    
            var idProvParameter = idProv != null ?
                new ObjectParameter("idProv", idProv) :
                new ObjectParameter("idProv", typeof(string));
    
            var idDistParameter = idDist != null ?
                new ObjectParameter("idDist", idDist) :
                new ObjectParameter("idDist", typeof(string));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var provinciaParameter = provincia != null ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("Distrito", distrito) :
                new ObjectParameter("Distrito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarUbigeo", id_ubigeoParameter, idDepaParameter, idProvParameter, idDistParameter, departamentoParameter, provinciaParameter, distritoParameter);
        }
    
        public virtual int usp_InsertLocal(string direccion, string telefono, string correo, string administrador, string ubigeo)
        {
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var administradorParameter = administrador != null ?
                new ObjectParameter("Administrador", administrador) :
                new ObjectParameter("Administrador", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertLocal", direccionParameter, telefonoParameter, correoParameter, administradorParameter, ubigeoParameter);
        }
    
        public virtual ObjectResult<usp_ListarAdmins_Result> usp_ListarAdmins()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAdmins_Result>("usp_ListarAdmins");
        }
    
        public virtual ObjectResult<usp_ListarCitas_Result> usp_ListarCitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCitas_Result>("usp_ListarCitas");
        }
    
        public virtual ObjectResult<usp_ListarConsultorio_Result> usp_ListarConsultorio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarConsultorio_Result>("usp_ListarConsultorio");
        }
    
        public virtual ObjectResult<usp_ListarLocal_Result> usp_ListarLocal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarLocal_Result>("usp_ListarLocal");
        }
    
        public virtual ObjectResult<usp_ListarLocales_Result> usp_ListarLocales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarLocales_Result>("usp_ListarLocales");
        }
    
        public virtual ObjectResult<usp_ListarPaciente_Result> usp_ListarPaciente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPaciente_Result>("usp_ListarPaciente");
        }
    
        public virtual ObjectResult<usp_ListarPsicologo_Result> usp_ListarPsicologo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPsicologo_Result>("usp_ListarPsicologo");
        }
    
        public virtual ObjectResult<usp_ListarTratamiento_Result> usp_ListarTratamiento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarTratamiento_Result>("usp_ListarTratamiento");
        }
    
        public virtual ObjectResult<usp_ListarUbigeo_Result> usp_ListarUbigeo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUbigeo_Result>("usp_ListarUbigeo");
        }
    
        public virtual ObjectResult<usp_ObtenerDatosCitaPorPaciente_Result> usp_ObtenerDatosCitaPorPaciente(Nullable<int> codigoPaciente)
        {
            var codigoPacienteParameter = codigoPaciente.HasValue ?
                new ObjectParameter("CodigoPaciente", codigoPaciente) :
                new ObjectParameter("CodigoPaciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerDatosCitaPorPaciente_Result>("usp_ObtenerDatosCitaPorPaciente", codigoPacienteParameter);
        }
    
        public virtual ObjectResult<usp_PsicologosDisponiblesEnHora_Result> usp_PsicologosDisponiblesEnHora(Nullable<System.TimeSpan> horaInicio)
        {
            var horaInicioParameter = horaInicio.HasValue ?
                new ObjectParameter("horaInicio", horaInicio) :
                new ObjectParameter("horaInicio", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PsicologosDisponiblesEnHora_Result>("usp_PsicologosDisponiblesEnHora", horaInicioParameter);
        }
    
        public virtual int usp_RegistrarHistorialClinico(Nullable<int> vidPac, Nullable<int> vidPsico, Nullable<System.DateTime> vfecInicio, Nullable<System.DateTime> vfecFin)
        {
            var vidPacParameter = vidPac.HasValue ?
                new ObjectParameter("vidPac", vidPac) :
                new ObjectParameter("vidPac", typeof(int));
    
            var vidPsicoParameter = vidPsico.HasValue ?
                new ObjectParameter("vidPsico", vidPsico) :
                new ObjectParameter("vidPsico", typeof(int));
    
            var vfecInicioParameter = vfecInicio.HasValue ?
                new ObjectParameter("vfecInicio", vfecInicio) :
                new ObjectParameter("vfecInicio", typeof(System.DateTime));
    
            var vfecFinParameter = vfecFin.HasValue ?
                new ObjectParameter("vfecFin", vfecFin) :
                new ObjectParameter("vfecFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RegistrarHistorialClinico", vidPacParameter, vidPsicoParameter, vfecInicioParameter, vfecFinParameter);
        }
    
        public virtual ObjectResult<usp_TotalPacientesAnual_Result> usp_TotalPacientesAnual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TotalPacientesAnual_Result>("usp_TotalPacientesAnual");
        }
    
        public virtual int usp_UpdateAdministrador(Nullable<int> id_admin, string nombre, string apellido, string telefono, string correo, string ubigeo, Nullable<int> estado, Nullable<System.DateTime> fecha_registro, Nullable<System.DateTime> fecha_ult_modificacion, string usuario_registro, string usuario_ult_modificacion)
        {
            var id_adminParameter = id_admin.HasValue ?
                new ObjectParameter("id_admin", id_admin) :
                new ObjectParameter("id_admin", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("Fecha_registro", fecha_registro) :
                new ObjectParameter("Fecha_registro", typeof(System.DateTime));
    
            var fecha_ult_modificacionParameter = fecha_ult_modificacion.HasValue ?
                new ObjectParameter("Fecha_ult_modificacion", fecha_ult_modificacion) :
                new ObjectParameter("Fecha_ult_modificacion", typeof(System.DateTime));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateAdministrador", id_adminParameter, nombreParameter, apellidoParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter, fecha_registroParameter, fecha_ult_modificacionParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_UpdateConsultorio(Nullable<int> id_Consultorio, string telefono, Nullable<System.TimeSpan> inicio, Nullable<System.TimeSpan> fin, Nullable<int> id_local, Nullable<System.DateTime> fecha_registro, Nullable<System.DateTime> fecha_ult_modificacion, string usuario_registro, string usuario_ult_modificacion)
        {
            var id_ConsultorioParameter = id_Consultorio.HasValue ?
                new ObjectParameter("id_Consultorio", id_Consultorio) :
                new ObjectParameter("id_Consultorio", typeof(int));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.TimeSpan));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(System.TimeSpan));
    
            var id_localParameter = id_local.HasValue ?
                new ObjectParameter("Id_local", id_local) :
                new ObjectParameter("Id_local", typeof(int));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("Fecha_registro", fecha_registro) :
                new ObjectParameter("Fecha_registro", typeof(System.DateTime));
    
            var fecha_ult_modificacionParameter = fecha_ult_modificacion.HasValue ?
                new ObjectParameter("Fecha_ult_modificacion", fecha_ult_modificacion) :
                new ObjectParameter("Fecha_ult_modificacion", typeof(System.DateTime));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateConsultorio", id_ConsultorioParameter, telefonoParameter, inicioParameter, finParameter, id_localParameter, fecha_registroParameter, fecha_ult_modificacionParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_UpdateLocal(Nullable<int> id_local, string direccion, string telefono, string correo, Nullable<int> id_administrador, string id_ubigeo, string usuario_ult_modificacion)
        {
            var id_localParameter = id_local.HasValue ?
                new ObjectParameter("id_local", id_local) :
                new ObjectParameter("id_local", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var id_administradorParameter = id_administrador.HasValue ?
                new ObjectParameter("Id_administrador", id_administrador) :
                new ObjectParameter("Id_administrador", typeof(int));
    
            var id_ubigeoParameter = id_ubigeo != null ?
                new ObjectParameter("Id_ubigeo", id_ubigeo) :
                new ObjectParameter("Id_ubigeo", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateLocal", id_localParameter, direccionParameter, telefonoParameter, correoParameter, id_administradorParameter, id_ubigeoParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_UpdatePaciente(Nullable<int> id_paciente, string nombre, string apellido, string genero, string telefono, string correo, string ubigeo, Nullable<int> estado, byte[] foto, string usuario_ult_modificacion, Nullable<System.DateTime> fecha_Naci)
        {
            var id_pacienteParameter = id_paciente.HasValue ?
                new ObjectParameter("id_paciente", id_paciente) :
                new ObjectParameter("id_paciente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            var fecha_NaciParameter = fecha_Naci.HasValue ?
                new ObjectParameter("Fecha_Naci", fecha_Naci) :
                new ObjectParameter("Fecha_Naci", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdatePaciente", id_pacienteParameter, nombreParameter, apellidoParameter, generoParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter, fotoParameter, usuario_ult_modificacionParameter, fecha_NaciParameter);
        }
    
        public virtual int usp_UpdatePsicologo(Nullable<int> id_psicologo, string nombre, string especialidad, string telefono, string correo, string ubigeo, Nullable<int> estado, byte[] foto, string usuario_ult_modificacion)
        {
            var id_psicologoParameter = id_psicologo.HasValue ?
                new ObjectParameter("id_psicologo", id_psicologo) :
                new ObjectParameter("id_psicologo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("Especialidad", especialidad) :
                new ObjectParameter("Especialidad", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var ubigeoParameter = ubigeo != null ?
                new ObjectParameter("Ubigeo", ubigeo) :
                new ObjectParameter("Ubigeo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdatePsicologo", id_psicologoParameter, nombreParameter, especialidadParameter, telefonoParameter, correoParameter, ubigeoParameter, estadoParameter, fotoParameter, usuario_ult_modificacionParameter);
        }
    
        public virtual int usp_UpdateTratamiento(Nullable<int> id_tratamiento, string descripcion, Nullable<System.DateTime> fecha_registro, Nullable<System.DateTime> fecha_ult_modificacion, string usuario_registro, string usuario_ult_modificacion)
        {
            var id_tratamientoParameter = id_tratamiento.HasValue ?
                new ObjectParameter("id_tratamiento", id_tratamiento) :
                new ObjectParameter("id_tratamiento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("Fecha_registro", fecha_registro) :
                new ObjectParameter("Fecha_registro", typeof(System.DateTime));
    
            var fecha_ult_modificacionParameter = fecha_ult_modificacion.HasValue ?
                new ObjectParameter("Fecha_ult_modificacion", fecha_ult_modificacion) :
                new ObjectParameter("Fecha_ult_modificacion", typeof(System.DateTime));
    
            var usuario_registroParameter = usuario_registro != null ?
                new ObjectParameter("Usuario_registro", usuario_registro) :
                new ObjectParameter("Usuario_registro", typeof(string));
    
            var usuario_ult_modificacionParameter = usuario_ult_modificacion != null ?
                new ObjectParameter("Usuario_ult_modificacion", usuario_ult_modificacion) :
                new ObjectParameter("Usuario_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateTratamiento", id_tratamientoParameter, descripcionParameter, fecha_registroParameter, fecha_ult_modificacionParameter, usuario_registroParameter, usuario_ult_modificacionParameter);
        }
    }
}
