//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_consultorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_consultorio()
        {
            this.tb_horario = new HashSet<tb_horario>();
        }
    
        public int id_consultorio { get; set; }
        public string telefono { get; set; }
        public Nullable<System.TimeSpan> inicio { get; set; }
        public Nullable<System.TimeSpan> fin { get; set; }
        public int id_local { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
        public Nullable<System.DateTime> Fecha_ult_modificacion { get; set; }
        public string Usuario_registro { get; set; }
        public string Usuario_ult_modificacion { get; set; }
    
        public virtual tb_local tb_local { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_horario> tb_horario { get; set; }
    }
}
