//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_psicologo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_psicologo()
        {
            this.tb_horario = new HashSet<tb_horario>();
        }
    
        public int id_psicologo { get; set; }
        public string nombre { get; set; }
        public string especialidad { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string id_ubigeo { get; set; }
        public Nullable<int> estado { get; set; }
        public byte[] foto { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
        public Nullable<System.DateTime> Fecha_ult_modificacion { get; set; }
        public string Usuario_registro { get; set; }
        public string Usuario_ult_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_horario> tb_horario { get; set; }
        public virtual tb_Ubigeo tb_Ubigeo { get; set; }
    }
}
