//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuarios
    {
        public string UsuarioID { get; set; }
        public string Pass_Usuario { get; set; }
        public int Niv_Usuario { get; set; }
        public bool est_usuario { get; set; }
    }
}
