//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacienteService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Clinica")]
    public partial class PacienteDC : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string DepartamentoField;
        
        private string DistritoField;
        
        private short EdadField;
        
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        private System.Nullable<System.DateTime> Fecha_RegistroField;
        
        private System.Nullable<System.DateTime> Fecha_ult_modificacionField;
        
        private string ProvinciaField;
        
        private string Usuario_RegistroField;
        
        private string Usuario_ult_modificacionField;
        
        private string apellidosField;
        
        private string correoField;
        
        private short estadeField;
        
        private short estadoField;
        
        private byte[] fotoField;
        
        private string generoField;
        
        private short id_pacienteField;
        
        private string id_ubigeoField;
        
        private string nombresField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true))
                {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistritoField, value) != true))
                {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Edad
        {
            get
            {
                return this.EdadField;
            }
            set
            {
                if ((this.EdadField.Equals(value) != true))
                {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                if ((this.FechaNacimientoField.Equals(value) != true))
                {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_Registro
        {
            get
            {
                return this.Fecha_RegistroField;
            }
            set
            {
                if ((this.Fecha_RegistroField.Equals(value) != true))
                {
                    this.Fecha_RegistroField = value;
                    this.RaisePropertyChanged("Fecha_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_ult_modificacion
        {
            get
            {
                return this.Fecha_ult_modificacionField;
            }
            set
            {
                if ((this.Fecha_ult_modificacionField.Equals(value) != true))
                {
                    this.Fecha_ult_modificacionField = value;
                    this.RaisePropertyChanged("Fecha_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true))
                {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_Registro
        {
            get
            {
                return this.Usuario_RegistroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.Usuario_RegistroField, value) != true))
                {
                    this.Usuario_RegistroField = value;
                    this.RaisePropertyChanged("Usuario_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_ult_modificacion
        {
            get
            {
                return this.Usuario_ult_modificacionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.Usuario_ult_modificacionField, value) != true))
                {
                    this.Usuario_ult_modificacionField = value;
                    this.RaisePropertyChanged("Usuario_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos
        {
            get
            {
                return this.apellidosField;
            }
            set
            {
                if ((object.ReferenceEquals(this.apellidosField, value) != true))
                {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.correoField, value) != true))
                {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short estade
        {
            get
            {
                return this.estadeField;
            }
            set
            {
                if ((this.estadeField.Equals(value) != true))
                {
                    this.estadeField = value;
                    this.RaisePropertyChanged("estade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                if ((this.estadoField.Equals(value) != true))
                {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] foto
        {
            get
            {
                return this.fotoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.fotoField, value) != true))
                {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.generoField, value) != true))
                {
                    this.generoField = value;
                    this.RaisePropertyChanged("genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short id_paciente
        {
            get
            {
                return this.id_pacienteField;
            }
            set
            {
                if ((this.id_pacienteField.Equals(value) != true))
                {
                    this.id_pacienteField = value;
                    this.RaisePropertyChanged("id_paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_ubigeo
        {
            get
            {
                return this.id_ubigeoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.id_ubigeoField, value) != true))
                {
                    this.id_ubigeoField = value;
                    this.RaisePropertyChanged("id_ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                if ((object.ReferenceEquals(this.nombresField, value) != true))
                {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.telefonoField, value) != true))
                {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PacienteService.IServicioPaciente")]
    public interface IServicioPaciente
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacienteResponse")]
        PacienteService.PacienteDC ConsultarPaciente(short id_paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacienteResponse")]
        System.Threading.Tasks.Task<PacienteService.PacienteDC> ConsultarPacienteAsync(short id_paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ListarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ListarPacienteResponse")]
        System.Collections.Generic.List<PacienteService.PacienteDC> ListarPaciente(short estade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ListarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ListarPacienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PacienteService.PacienteDC>> ListarPacienteAsync(short estade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/InsertarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/InsertarPacienteResponse")]
        bool InsertarPaciente(PacienteService.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/InsertarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/InsertarPacienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarPacienteAsync(PacienteService.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ActualizarPacienteResponse")]
        bool ActualizarPaciente(PacienteService.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ActualizarPacienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPacienteAsync(PacienteService.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/EliminarPacienteResponse")]
        bool EliminarPaciente(short id_paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/EliminarPacienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarPacienteAsync(short id_paciente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioPacienteChannel : PacienteService.IServicioPaciente, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioPacienteClient : System.ServiceModel.ClientBase<PacienteService.IServicioPaciente>, PacienteService.IServicioPaciente
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioPacienteClient() : 
                base(ServicioPacienteClient.GetDefaultBinding(), ServicioPacienteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioPaciente.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), ServicioPacienteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PacienteService.PacienteDC ConsultarPaciente(short id_paciente)
        {
            return base.Channel.ConsultarPaciente(id_paciente);
        }
        
        public System.Threading.Tasks.Task<PacienteService.PacienteDC> ConsultarPacienteAsync(short id_paciente)
        {
            return base.Channel.ConsultarPacienteAsync(id_paciente);
        }
        
        public System.Collections.Generic.List<PacienteService.PacienteDC> ListarPaciente(short estade)
        {
            return base.Channel.ListarPaciente(estade);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PacienteService.PacienteDC>> ListarPacienteAsync(short estade)
        {
            return base.Channel.ListarPacienteAsync(estade);
        }
        
        public bool InsertarPaciente(PacienteService.PacienteDC objPacienteDC)
        {
            return base.Channel.InsertarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarPacienteAsync(PacienteService.PacienteDC objPacienteDC)
        {
            return base.Channel.InsertarPacienteAsync(objPacienteDC);
        }
        
        public bool ActualizarPaciente(PacienteService.PacienteDC objPacienteDC)
        {
            return base.Channel.ActualizarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPacienteAsync(PacienteService.PacienteDC objPacienteDC)
        {
            return base.Channel.ActualizarPacienteAsync(objPacienteDC);
        }
        
        public bool EliminarPaciente(short id_paciente)
        {
            return base.Channel.EliminarPaciente(id_paciente);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPacienteAsync(short id_paciente)
        {
            return base.Channel.EliminarPacienteAsync(id_paciente);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPaciente))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPaciente))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Clinica/ServicioPaciente/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioPacienteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioPaciente);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioPacienteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioPaciente);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioPaciente,
        }
    }
}
